version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: node  
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: /bin/bash -c "while sleep 1000; do :; done"